### ISSUE TITLE
Proxy issue while running save_users_followers_info.py

### ISSUE THREAD

**Issue by hyestt** [ohld/igbot#1000]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### Describe your issue

Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.

**Comment by hyestt** [comment]
Hello, 

I've encountered this error while running save_users_followers_into_file.py in example folder. 
I set proxy parameter to None.  Anyone know how to solve this ?

2019-08-09 07:52:15,281 - INFO - Instabot Started
2019-08-09 07:52:15,381 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/si/fetch_headers/?challenge_type=signup&guid=f93b9e49b3c44db087eaecf0a3183d9b (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107639cf8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')))
2019-08-09 07:52:15,382 - CRITICAL - Not logged in!
Traceback (most recent call last):
  File "save_users_followers_into_file.py", line 28, in <module>
    followers = bot.get_user_followers(username)
  File "/Users/glen/anaconda3/lib/python3.7/site-packages/instabot/bot/bot.py", line 444, in get_user_followers
    return get_user_followers(self, user_id, nfollows)
  File "/Users/glen/anaconda3/lib/python3.7/site-packages/instabot/bot/bot_get.py", line 226, in get_user_followers
    user_id = self.convert_to_user_id(user_id)
  File "/Users/glen/anaconda3/lib/python3.7/site-packages/instabot/bot/bot.py", line 486, in convert_to_user_id
    return convert_to_user_id(self, usernames)
  File "/Users/glen/anaconda3/lib/python3.7/site-packages/instabot/bot/bot_get.py", line 363, in convert_to_user_id
    x = self.get_user_id_from_username(x)
  File "/Users/glen/anaconda3/lib/python3.7/site-packages/instabot/bot/bot.py", line 432, in get_user_id_from_username
    return get_user_id_from_username(self, username)
  File "/Users/glen/anaconda3/lib/python3.7/site-packages/instabot/bot/bot_get.py", line 197, in get_user_id_from_username
    self.api.search_username(username)
  File "/Users/glen/anaconda3/lib/python3.7/site-packages/instabot/api/api.py", line 904, in search_username
    return self.send_request(url)
  File "/Users/glen/anaconda3/lib/python3.7/site-packages/instabot/api/api.py", line 169, in send_request
    raise Exception(msg)
Exception: Not logged in!
2019-08-09 07:52:15,384 - INFO - Bot stopped. Worked: 1 day, 0:01:40.856259
2019-08-09 07:52:15,385 - INFO - Total requests: 54
