### ISSUE TITLE
running and waiting

### ISSUE THREAD

**Issue by 1bilebilsem** [ohld/igbot#1042]
nter your password: (it will not be shown due to security reasons - just start typing and press Enter)

i entered the password and i'm waiting for 10 minute there's nothing

**Comment by 1bilebilsem** [comment]
2019-09-10 20:34:29,436 - INFO - Instabot Started
Traceback (most recent call last):
  File "C:\Users\ahmet\OneDrive\Masaüstü\instabot-master\instabot\api\prepare.py", line 60, in check_secret
    login, password = f.readline().strip().split(":")
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/ahmet/OneDrive/Masaüstü/instabot-master/examples/autopost/auto_post.py", line 20, in <module>
    bot.login()
  File "C:\Users\ahmet\OneDrive\Masaüstü\instabot-master\instabot\bot\bot.py", line 369, in login
    if self.api.login(**args) is False:
  File "C:\Users\ahmet\OneDrive\Masaüstü\instabot-master\instabot\api\api.py", line 179, in login
    username, password = get_credentials(username=username)
  File "C:\Users\ahmet\OneDrive\Masaüstü\instabot-master\instabot\api\prepare.py", line 22, in get_credentials
    while not check_secret():
  File "C:\Users\ahmet\OneDrive\Masaüstü\instabot-master\instabot\api\prepare.py", line 73, in check_secret
    os.remove(SECRET_FILE)
PermissionError: [WinError 32] Dosya başka bir işlem tarafından kullanıldığından bu işlem dosyaya erişemiyor: 'secret.txt'

**Comment by ohld** [comment]
Can you try to update the instabot and try again? What script do you use? 

``` 
pip install -U instabot
```
