### ISSUE TITLE
When I run multi_script_CLI, it gives me the following error: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by dsovgut** [ohld/igbot#1168]
---

Error:

```python
runfile('/Users/Danya/instabot/examples/multi_script_CLI.py', wdir='/Users/Danya/instabot/examples')
Traceback (most recent call last):

  File "<ipython-input-1-81b9b0581be3>", line 1, in <module>
    runfile('/Users/Danya/instabot/examples/multi_script_CLI.py', wdir='/Users/Danya/instabot/examples')

  File "/Users/Danya/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/Users/Danya/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/Danya/instabot/examples/multi_script_CLI.py", line 638, in <module>
    setting_8 = int(lines[8].strip())

ValueError: invalid literal for int() with base 10: ''




runfile('/Users/Danya/instabot/examples/multi_script_CLI.py', wdir='/Users/Danya/instabot/examples')
Traceback (most recent call last):

  File "<ipython-input-2-81b9b0581be3>", line 1, in <module>
    runfile('/Users/Danya/instabot/examples/multi_script_CLI.py', wdir='/Users/Danya/instabot/examples')

  File "/Users/Danya/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/Users/Danya/opt/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/Danya/instabot/examples/multi_script_CLI.py", line 639, in <module>
    setting_9 = int(lines[9].strip())

ValueError: invalid literal for int() with base 10: ''
```

### Describe your issue

When I try to run multi_script_CLI, it gives me the following error: invalid literal for int() with base 10: ''. Why is this happening?

**Comment by michael-pisman** [comment]
Same here
```python
Traceback (most recent call last):
  File "multi_script_CLI.py", line 630, in <module>
    setting_0 = int(lines[0].strip())
ValueError: invalid literal for int() with base 10: ''
```

### Update:
So the issue is in the default parameters. I found that passing the int in the file will solve the issue. 
Edit manualy multi_script_CLI.py. I used emacs, you can use your favorite editor
`nano multi_script_CLI.py`

Go to the line that causes error, and change lines[n].strip() to a number
```python
setting_0 = int(1000)
setting_1 = int(1000)
setting_2 = int(350)
setting_3 = int(350)
setting_4 = int(100)
setting_5 = int(100)
setting_6 = int(2000)
setting_7 = int(10)
setting_8 = int(7500)
setting_9 = int(10)
setting_10 = int(10)
setting_11 = int(2)
setting_12 = int(3)
setting_13 = int(10)
setting_14 = int(10)
setting_15 = int(30)
setting_16 = int(30)
setting_17 = int(60)
setting_18 = "None"
```

P.S. you probably can remove int(), since no conversion needed, but I was lazy...
