### ISSUE TITLE
Exception: Not logged in! error

### ISSUE THREAD

**Issue by soyfode** [ohld/igbot#1229]
import instabot
mi_bot = instabot.Bot()
mi_bot.login(username='user', password='password')
mi_bot.follow_followers('x',10)

2020-01-13 18:02:33,603 - INFO - Instabot Started
2020-01-13 18:02:33,605 - INFO - PRE-LOGIN FLOW!... 
2020-01-13 18:02:34,250 - DEBUG - <Response [200]>
2020-01-13 18:02:34,468 - DEBUG - <Response [200]>
2020-01-13 18:02:34,699 - DEBUG - <Response [200]>
2020-01-13 18:02:34,913 - DEBUG - <Response [200]>
2020-01-13 18:02:35,121 - DEBUG - <Response [200]>
2020-01-13 18:02:36,075 - DEBUG - <Response [400]>
2020-01-13 18:02:36,075 - ERROR - Request returns 400 error!
2020-01-13 18:02:36,077 - INFO - Instagram's error message: challenge_required
2020-01-13 18:02:36,077 - INFO - Error type: checkpoint_challenge_required
2020-01-13 18:02:36,078 - INFO - Checkpoint challenge required...
2020-01-13 18:02:36,079 - INFO - Follow followers of: x
2020-01-13 18:02:36,080 - CRITICAL - Not logged in!
Traceback (most recent call last):

  File "<ipython-input-12-6aabc99a331e>", line 4, in <module>
    mi_bot.follow_followers('x',10)

  File "C:\Users\59173\AppData\Local\Programs\Python\Python36\lib\site-packages\instabot\bot\bot.py", line 830, in follow_followers
    return follow_followers(self, user_id, nfollows)

  File "C:\Users\59173\AppData\Local\Programs\Python\Python36\lib\site-packages\instabot\bot\bot_follow.py", line 136, in follow_followers
    followers = self.get_user_followers(user_id, nfollows)

  File "C:\Users\59173\AppData\Local\Programs\Python\Python36\lib\site-packages\instabot\bot\bot.py", line 608, in get_user_followers
    return get_user_followers(self, user_id, nfollows)

  File "C:\Users\59173\AppData\Local\Programs\Python\Python36\lib\site-packages\instabot\bot\bot_get.py", line 236, in get_user_followers
    user_id = self.convert_to_user_id(user_id)

  File "C:\Users\59173\AppData\Local\Programs\Python\Python36\lib\site-packages\instabot\bot\bot.py", line 653, in convert_to_user_id
    return convert_to_user_id(self, usernames)

  File "C:\Users\59173\AppData\Local\Programs\Python\Python36\lib\site-packages\instabot\bot\bot_get.py", line 491, in convert_to_user_id
    x = self.get_user_id_from_username(x)

  File "C:\Users\59173\AppData\Local\Programs\Python\Python36\lib\site-packages\instabot\bot\bot.py", line 596, in get_user_id_from_username
    return get_user_id_from_username(self, username)

  File "C:\Users\59173\AppData\Local\Programs\Python\Python36\lib\site-packages\instabot\bot\bot_get.py", line 207, in get_user_id_from_username
    self.api.search_username(username)

  File "C:\Users\59173\AppData\Local\Programs\Python\Python36\lib\site-packages\instabot\api\api.py", line 1504, in search_username
    return self.send_request(url)

  File "C:\Users\59173\AppData\Local\Programs\Python\Python36\lib\site-packages\instabot\api\api.py", line 427, in send_request
    raise Exception(msg)

Exception: Not logged in!

**Comment by bruvv** [comment]
https://github.com/instagrambot/instabot/issues/1224
