### ISSUE TITLE
[BUG] welcome_message.py  <Response [200]>

### ISSUE THREAD

**Issue by Abdulsamipy** [ohld/igbot#1248]
**Describe the bug**

hi guy, so i was trying to run welcome_message.py , no message is being sent to any of the new followers and i have been getting following error
` GET to endpoint: news/inbox/?limited_activity=true&show_su=true returned response: <Response [200]>`

**Screenshots**

![Capture](https://user-images.githubusercontent.com/58009877/72837642-9af6d600-3cb0-11ea-908e-e263cd1e97ae.PNG)

log:
```
2020-01-22 00:41:06,018 - INFO - LOGIN FLOW! Just logged-in: False
2020-01-22 00:41:07,393 - DEBUG - POST to endpoint: feed/timeline/ returned response: <Response [200]>
2020-01-22 00:41:08,006 - DEBUG - POST to endpoint: feed/reels_tray/ returned response: <Response [200]>
2020-01-22 00:41:08,006 - INFO - Logged-in successfully as 'xxxx'!
2020-01-22 00:41:08,772 - DEBUG - GET to endpoint: news/inbox/?limited_activity=true&show_su=true returned response: <Response [200]>
2020-01-22 00:41:29,866 - DEBUG - GET to endpoint: news/inbox/?limited_activity=true&show_su=true returned response: <Response [200]>
2020-01-22 00:41:50,764 - DEBUG - GET to endpoint: news/inbox/?limited_activity=true&show_su=true returned response: <Response [200]>
2020-01-22 00:42:11,431 - DEBUG - GET to endpoint: news/inbox/?limited_activity=true&show_su=true returned response: <Response [200]>
```

**To Reproduce**

1. Edit '...'
2. Run '....'

**Expected behavior**

message new followers

**Comment by bruvv** [comment]
Try the development branch

**Comment by Abdulsamipy** [comment]
> Try the development branch

![Capture](https://user-images.githubusercontent.com/58009877/72839573-566d3980-3cb4-11ea-8862-bb50b3ec6197.PNG)
2020-01-22 10:16:39,462 - INFO - LOGIN FLOW! Just logged-in: False
2020-01-22 10:16:43,493 - INFO - Logged-in successfully as 
2020-01-22 10:20:35,520 - INFO - Total requests: 4

**Comment by Abdulsamipy** [comment]
@bruvv i know it's not related to this issue but when i tried to run "multi_script_CLI.py" (from dev branch)
and it's giving the follow log 

`Looks like setting are broken
Let's make new one
Traceback (most recent call last):
  File "C:\Users\xxxxx\instabot-development\examples\multi_script_CLI.py", line 626, in <module>
    setting_input()
  File "C:\Users\xxxxx\instabot-development\examples\multi_script_CLI.py", line 118, in setting_input
    with open(settings, "w") as f:
NameError: name 'settings' is not defined
`

**Comment by andreagiugio** [comment]
> **Describe the bug**
> 
> hi guy, so i was trying to run welcome_message.py , no message is being sent to any of the new followers and i have been getting following error
> ` GET to endpoint: news/inbox/?limited_activity=true&show_su=true returned response: <Response [200]>`
> 
> **Screenshots**
> 
> ![Capture](https://user-images.githubusercontent.com/58009877/72837642-9af6d600-3cb0-11ea-908e-e263cd1e97ae.PNG)
> 
> log:
> 
> ```
> 2020-01-22 00:41:06,018 - INFO - LOGIN FLOW! Just logged-in: False
> 2020-01-22 00:41:07,393 - DEBUG - POST to endpoint: feed/timeline/ returned response: <Response [200]>
> 2020-01-22 00:41:08,006 - DEBUG - POST to endpoint: feed/reels_tray/ returned response: <Response [200]>
> 2020-01-22 00:41:08,006 - INFO - Logged-in successfully as 'xxxx'!
> 2020-01-22 00:41:08,772 - DEBUG - GET to endpoint: news/inbox/?limited_activity=true&show_su=true returned response: <Response [200]>
> 2020-01-22 00:41:29,866 - DEBUG - GET to endpoint: news/inbox/?limited_activity=true&show_su=true returned response: <Response [200]>
> 2020-01-22 00:41:50,764 - DEBUG - GET to endpoint: news/inbox/?limited_activity=true&show_su=true returned response: <Response [200]>
> 2020-01-22 00:42:11,431 - DEBUG - GET to endpoint: news/inbox/?limited_activity=true&show_su=true returned response: <Response [200]>
> ```
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Edit '...'
> 2. Run '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> 
> message new followers

I have the same problem

**Comment by bruvv** [comment]
It's not an error
