### ISSUE TITLE
[BUG] cannot login

### ISSUE THREAD

**Issue by loookazs** [ohld/igbot#1261]
**Describe the bug**

I run an ultimate.py example and I cannot login. There's a checpoint_challlenge_required. I turned off the 2fa. I checked similar issues but didn't find the answer for me.

**Screenshots**
--

**To Reproduce**

Just run the **ultimate.py**. Looks like follow_followers.txt etc is ok. Well, I cannot tell because it's not looging in.

**Expected behavior**

I obviously expect bot to log in.

**Screenshots/logs**

2020-01-24 22:09:35,069 - INFO - PRE-LOGIN FLOW!... 
2020-01-24 22:09:35,393 - DEBUG - POST to endpoint: accounts/read_msisdn_header/ returned response: <Response [200]>
2020-01-24 22:09:35,596 - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2020-01-24 22:09:35,831 - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2020-01-24 22:09:36,018 - DEBUG - POST to endpoint: attribution/log_attribution/ returned response: <Response [200]>
2020-01-24 22:09:36,207 - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2020-01-24 22:09:38,318 - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-01-24 22:09:38,334 - DEBUG - Responsecode indicates error; response content: b'{"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/2274233643/PRyIds8ZiB/", "api_path": "/challenge/2274233643/PRyIds8ZiB/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}'
2020-01-24 22:09:38,349 - ERROR - Request returns 400 error!
2020-01-24 22:09:38,349 - INFO - Instagram's error message: challenge_required
2020-01-24 22:09:38,365 - INFO - Error type: checkpoint_challenge_required
2020-01-24 22:09:38,380 - INFO - Checkpoint challenge required...

Current script's schedule:
Going to follow followers of: ['user']
Going to follow following of: []
Going to like hashtags: ['hashtag']
Going to like users: []

2020-01-23 21:04:17,851 - INFO - Follow followers of: (...)
2020-01-23 21:04:17,851 - CRITICAL - Not logged in!
Traceback (most recent call last):
  File "C:\Users\(...)Lib\site-packages\examples\ultimate\ultimate.py", line 43, in <module>
    func(**arg)
  File "C:\Users\(...)lib\site-packages\instabot\bot\bot.py", line 830, in follow_followers
    return follow_followers(self, user_id, nfollows)
  File "C:\Users\(...)lib\site-packages\instabot\bot\bot_follow.py", line 136, in follow_followers
    followers = self.get_user_followers(user_id, nfollows)
  File "C:\Users\(...)lib\site-packages\instabot\bot\bot.py", line 608, in get_user_followers
    return get_user_followers(self, user_id, nfollows)
  File "C:\Users\(...)lib\site-packages\instabot\bot\bot_get.py", line 236, in get_user_followers
    user_id = self.convert_to_user_id(user_id)
  File "C:\Users\(...)lib\site-packages\instabot\bot\bot.py", line 653, in convert_to_user_id
    return convert_to_user_id(self, usernames)
  File "C:\Users\(...)lib\site-packages\instabot\bot\bot_get.py", line 491, in convert_to_user_id
    x = self.get_user_id_from_username(x)
  File "C:\Users\(...)lib\site-packages\instabot\bot\bot.py", line 596, in get_user_id_from_username
    return get_user_id_from_username(self, username)
  File "C:\Users\(...)lib\site-packages\instabot\bot\bot_get.py", line 207, in get_user_id_from_username
    self.api.search_username(username)
  File "C:\Users\(...)lib\site-packages\instabot\api\api.py", line 1515, in search_username
    return self.send_request(url)
  File "C:\Users\(...)lib\site-packages\instabot\api\api.py", line 427, in send_request
    raise Exception(msg)
Exception: Not logged in!

**Comment by renaldas112** [comment]
Literally nothing works, not a single script work in the whole folder, or I'm just doing it wrong :/ I tried Ultimate.py, opened with IDLE, ran the module, inserted my username and I get this:


Traceback (most recent call last):
  File "C:\Users\Dell E7440\Desktop\Instabot\instabot\examples\ultimate\ultimate.py", line 19, in <module>
    bot.login()
  File "C:\Python27\lib\site-packages\instabot\bot\bot.py", line 436, in login
    if self.api.login(**args) is False:
  File "C:\Python27\lib\site-packages\instabot\api\api.py", line 190, in login
    username, password = get_credentials(username=username)
  File "C:\Python27\lib\site-packages\instabot\api\prepare.py", line 21, in get_credentials
    while not check_secret():
  File "C:\Python27\lib\site-packages\instabot\api\prepare.py", line 80, in check_secret
    add_credentials()
  File "C:\Python27\lib\site-packages\instabot\api\prepare.py", line 11, in add_credentials
    f.write(str(input("Enter your username: ")) + ":")
  File "<string>", line 1, in <module>
NameError: name 'atsarginisssss' is not defined

**Comment by bruvv** [comment]
It's been mentioned before a couple of times how to fix it. When I got the development branch figured out I'll see if I can automate this process.

**Comment by loookazs** [comment]
I couldn't find these fixes. Would you care to show them?

**Comment by ivanstnv** [comment]
Having the same problem for the last couple of days ... @bruvv Where is a fix mentioned? I would be really thankful if you could drop a link <3

**Comment by karera-s** [comment]
I am in trouble with the same problem. Help me.

**Comment by renaldas112** [comment]
clossed it even though i hasnt been fixed :D

**Comment by bruvv** [comment]
@renaldas112 it has been mentioned multiple times over and over how to fix this. there is no fix needed for it since it is already avaible.
See here: https://github.com/instagrambot/instabot/issues?utf8=%E2%9C%93&q=is%3Aissue+checkpoint+required+

**Comment by loookazs** [comment]
@bruvv please show a particular solution. Before writing about the issue I searched through the github and I couldn't find it. You are right - it was mentioned many times but **no solution was given**. In the search filter you gave it's the same situation - **a lot of closed or stale queries with no answers** with links to other issues also with no fixes.

**Comment by bruvv** [comment]
Alright i digged into it and it is instagram blocking your account. If this happens than you have to remove the current cookie file, for example:
```
username_uuid_and_cookie.json
```
Remove the following file as wel: `secret.txt`
Change your password in instagram, wait 24 hours and readd your account.

**Comment by ivanstnv** [comment]
Worked for me. Thank you @bruvv  <3

**Comment by karera-s** [comment]
@bruvv Hello. I can't go further from this state. I deleted secret.txt but it did not help.Is there a solution?

```
2020-01-30 11:51:45,022 - INFO - Instabot Started
Your file is broken. We will delete it and try again.
We need to create a text file 'secret.txt' where we will store your login and password from Instagram.
Don't worry. It will be stored locally.
Enter your username: *****
Traceback (most recent call last):
  File "like_hashtags.py", line 24, in <module>
    bot.login(username=args.u, password=args.p, proxy=args.proxy)
  File "/Users/kareras/Library/Python/2.7/lib/python/site-packages/instabot/bot/bot.py", line 436, in login
    if self.api.login(**args) is False:
  File "/Users/kareras/Library/Python/2.7/lib/python/site-packages/instabot/api/api.py", line 190, in login
    username, password = get_credentials(username=username)
  File "/Users/kareras/Library/Python/2.7/lib/python/site-packages/instabot/api/prepare.py", line 21, in get_credentials
    while not check_secret():
  File "/Users/kareras/Library/Python/2.7/lib/python/site-packages/instabot/api/prepare.py", line 80, in check_secret
    add_credentials()
  File "/Users/kareras/Library/Python/2.7/lib/python/site-packages/instabot/api/prepare.py", line 11, in add_credentials
    f.write(str(input("Enter your username: ")) + ":")
  File "<string>", line 1, in <module>
NameError: name '*****' is not defined
```

**Comment by bruvv** [comment]
This is another issue you're having and this has been fixed in the development branch. Closing this issue.
