### ISSUE TITLE
[BUG] The "caption" does not accept any language except English

### ISSUE THREAD

**Issue by egyjs** [ohld/igbot#1265]
**Example file**

```
/examples/photos/upload_photos.py
```

**Describe the bug**

i can't write any other language for example 'arabic'

`python upload_photos.py -photo {photo_name} -caption "تجربة"`

**Log**

```
2020-01-28 08:50:25,175 - INFO - Instabot Started
2020-01-28 08:50:25,263 - DEBUG - Loading cookies
2020-01-28 08:50:25,264 - DEBUG - Loading uuids
2020-01-28 08:50:25,264 - INFO - Recovery from society.screen_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 105.0.0.18.119 Android (28/9.0; 420dpi; 1080x2260; OnePlus; GM1903; OnePlus7; qcom; en_US)
- phone_id=625abb4a-ea97-4e8c-aa3c-405d6eb3542a
- uuid=33cf1beb-a4f0-415b-a1e0-6c0a8b07cc0b
- client_session_id=ff193a56-55d7-45cd-a8e3-e4872d0a920f
- device_id=android-8fae5976fac8a021
2020-01-28 08:50:25,264 - INFO - LOGIN FLOW! Just logged-in: False
2020-01-28 08:50:26,505 - DEBUG - POST to endpoint: feed/timeline/ returned response: <Response [200]>
2020-01-28 08:50:26,888 - DEBUG - POST to endpoint: feed/reels_tray/ returned response: <Response [200]>
2020-01-28 08:50:26,896 - INFO - Logged-in successfully as 'society.screen'!
2020-01-28 08:50:26,897 - INFO - Checking test1.jpg
--- Logging error ---
Traceback (most recent call last):
  File "/home/fk48k43208g6/.local/lib/python3.4/logging/__init__.py", line 980, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 74-83: ordinal not in range(128)
Call stack:
  File "upload_photos.py", line 57, in <module>
    pic=pic, caption=caption
Message: 'Uploading pic `test1.jpg` with caption: `\udcd8\udcaa\udcd8\udcac\udcd8\udcb1\udcd8\udca8\udcd8\udca9`'
```

**Expected behavior**

i need to write in Arabic or even Chinese, so when I do this it comes to me as question marks

![image](https://user-images.githubusercontent.com/12745270/73280294-5a8edf00-41ff-11ea-85b9-d927da4c1e77.png)

**Comment by bruvv** [comment]
Please try the new version in development branch (https://github.com/instagrambot/instabot/commit/bab1074942868a4382c5faae96d1e89b4c206ef9)
