### ISSUE TITLE
[BUG] Checkpoint challenge required...

### ISSUE THREAD

**Issue by ChadLei** [ohld/igbot#1279]
**Example file**

```
download_photos_by_user.py
```

**Describe the bug**

Giving 400 error, challenge interrupts logging in

**Log**

```
2020-02-05 15:12:26,059 - INFO - PRE-LOGIN FLOW!... 
2020-02-05 15:12:26,427 - DEBUG - POST to endpoint: accounts/read_msisdn_header/ returned response: <Response [200]>
2020-02-05 15:12:26,484 - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2020-02-05 15:12:26,564 - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2020-02-05 15:12:26,747 - DEBUG - POST to endpoint: attribution/log_attribution/ returned response: <Response [200]>
2020-02-05 15:12:26,822 - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2020-02-05 15:12:28,784 - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-02-05 15:12:28,784 - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/6298157946/ZsxIB9PczV/", "api_path": "/challenge/6298157946/ZsxIB9PczV/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}
2020-02-05 15:12:28,784 - ERROR - Request returns 400 error!
2020-02-05 15:12:28,784 - INFO - Instagram's error message: challenge_required
2020-02-05 15:12:28,784 - INFO - Error type: checkpoint_challenge_required
2020-02-05 15:12:28,785 - INFO - Checkpoint challenge required...
2020-02-05 15:12:28,785 - CRITICAL - Not logged in!
Traceback (most recent call last):
  File "instagram.py", line 27, in <module>
    medias = bot.get_total_user_medias(args.username)
  File "/Users/chad.lei/Library/Python/2.7/lib/python/site-packages/instabot/bot/bot.py", line 560, in get_total_user_medias
    return get_total_user_medias(self, user_id)
  File "/Users/chad.lei/Library/Python/2.7/lib/python/site-packages/instabot/bot/bot_get.py", line 100, in get_total_user_medias
    user_id = self.convert_to_user_id(user_id)
  File "/Users/chad.lei/Library/Python/2.7/lib/python/site-packages/instabot/bot/bot.py", line 653, in convert_to_user_id
    return convert_to_user_id(self, usernames)
  File "/Users/chad.lei/Library/Python/2.7/lib/python/site-packages/instabot/bot/bot_get.py", line 491, in convert_to_user_id
    x = self.get_user_id_from_username(x)
  File "/Users/chad.lei/Library/Python/2.7/lib/python/site-packages/instabot/bot/bot.py", line 596, in get_user_id_from_username
    return get_user_id_from_username(self, username)
  File "/Users/chad.lei/Library/Python/2.7/lib/python/site-packages/instabot/bot/bot_get.py", line 207, in get_user_id_from_username
    self.api.search_username(username)
  File "/Users/chad.lei/Library/Python/2.7/lib/python/site-packages/instabot/api/api.py", line 1515, in search_username
    return self.send_request(url)
  File "/Users/chad.lei/Library/Python/2.7/lib/python/site-packages/instabot/api/api.py", line 427, in send_request
    raise Exception(msg)
Exception: Not logged in!

```

**To Reproduce**

After write "python scriptname.py param" and select my account, it gives "Exception: Not logged in!".

**Expected behavior**

Successfully login and download pics 

**Additional context**

**Version**

Python version (`python -v`): 3.8
OS: MacOS

**Comment by bruvv** [comment]
You python version doesn't match. In your log file it says 2.7 and you say it's 3.8. Also this has been answered multiple times already.

**Comment by BiGaripAdam** [comment]
@ChadLei did you solve this "Checkpoint challenge required" problem?

**Comment by bruvv** [comment]
Search. You should change your password and remove your json and you should delete your secret.txt file and relogin

**Comment by ChadLei** [comment]
it wasn't solved yet. my apologies for putting the wrong python version on there, yes I'm using 2.7. deleted all the files and changed my password, same error. its a matter of the challenge_required, how do yall avoid this?

**Comment by ChadLei** [comment]
@bruvv I haven't found a solid solution to this, would you mind pointing me towards one if you think it matches this issue? does python version matter?
