### ISSUE TITLE
[BUG] Cannot login

### ISSUE THREAD

**Issue by thehackedone** [ohld/igbot#1310]
Every time I try to login, I haven't changed anything seems like sometimes it works sometimes it doesn't anymore...

Traceback (most recent call last):
  File "c:\users\soul\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\soul\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Soul\AppData\Local\Programs\Python\Python36-32\Scripts\instabot-py.exe\__main__.py", line 9, in <module>
  File "c:\users\soul\appdata\local\programs\python\python36-32\lib\site-packages\instabot_py\__main__.py", line 395, in main
    bot = InstaBot(**configdict)
  File "c:\users\soul\appdata\local\programs\python\python36-32\lib\site-packages\instabot_py\instabot.py", line 365, in __init__
    self.login()
  File "c:\users\soul\appdata\local\programs\python\python36-32\lib\site-packages\instabot_py\instabot.py", line 589, in login
    self.user_id = self.get_user_id_by_username(self.user_login)
  File "c:\users\soul\appdata\local\programs\python\python36-32\lib\site-packages\instabot_py\instabot.py", line 392, in get_user_id_by_username
    "window._sharedData = (.*?);</script>", info.text, re.DOTALL
AttributeError: 'NoneType' object has no attribute 'group'

**Example file**

```
If you ran an example file specify it here.
```

**Describe the bug**

**Log**

```
here
```

**To Reproduce**

(EXAMPLE:) Steps to reproduce the behavior:
1. Run file:
2. Edit '...'
3. Run '....'

**Expected behavior**

**Additional context**

**Version**

Python version (`python -v`):
OS: Win/Linux/MacOS

**Comment by thehackedone** [comment]
so I assume I am either an idiot or its broken, I realize you have a template, but not everyone wants to follow that I will just use something that works better then this pile.
