### ISSUE TITLE
KeyError: 'ds_user_id'

### ISSUE THREAD

**Issue by BeatKO** [ohld/igbot#1337]
using this script
python3 like_hashtags.py party

getting this error:

```
2020-02-29 17:34:04,970 - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-02-29 17:34:08,146 - ERROR - Request returns 400 error!
2020-02-29 17:34:08,146 - INFO - Instagram's error message: challenge_required
2020-02-29 17:34:08,146 - INFO - Error type: checkpoint_challenge_required
2020-02-29 17:34:08,146 - INFO - Going to like media with hashtag #party.
Traceback (most recent call last):        
  File "like_hashtags.py", line 26, in <module>
    bot.like_hashtag(hashtag)
  File "/usr/local/lib/python3.6/dist-packages/instabot/bot/bot.py", line 734, in like_hashtag
    return like_hashtag(self, hashtag, amount)
  File "/usr/local/lib/python3.6/dist-packages/instabot/bot/bot_like.py", line 239, in like_hashtag
    medias = self.get_total_hashtag_medias(hashtag, amount)
  File "/usr/local/lib/python3.6/dist-packages/instabot/bot/bot.py", line 582, in get_total_hashtag_medias
    return get_total_hashtag_medias(self, hashtag, amount, filtration)
  File "/usr/local/lib/python3.6/dist-packages/instabot/bot/bot_get.py", line 139, in get_total_hashtag_medias
    medias = self.api.get_total_hashtag_feed(hashtag, amount)
  File "/usr/local/lib/python3.6/dist-packages/instabot/api/api.py", line 1493, in get_total_hashtag_feed
    self.get_hashtag_feed(hashtag_str, next_max_id)
  File "/usr/local/lib/python3.6/dist-packages/instabot/api/api.py", line 1170, in get_hashtag_feed
    ).format(hashtag=hashtag, max_id=max_id, rank_token=self.rank_token)
  File "/usr/local/lib/python3.6/dist-packages/instabot/api/api.py", line 634, in rank_token
    return "{}_{}".format(self.user_id, self.uuid)
  File "/usr/local/lib/python3.6/dist-packages/instabot/api/api.py", line 630, in user_id
    return self.cookie_dict["ds_user_id"]
KeyError: 'ds_user_id'
```

**Comment by soulpawa** [comment]
got the same problem
