### ISSUE TITLE
[BUG] Error type: checkpoint_challenge_required

### ISSUE THREAD

**Issue by nizarganteng** [ohld/igbot#1339]
**Example file**

```
comment_hashtags
```

**Describe the bug**
I think you need make script saving cookies ,so when i accept challenge login ,this challenge in next login is not show again

**Log**

```
2020-03-02 21:31:18,774 - INFO - Instabot version: 0.112.0 Started
Which account do you want to use? (Type number)
1: myusername
0: add another account.
-1: delete all accounts.
1
2020-03-02 21:31:20,351 - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-03-02 21:31:24,081 - ERROR - Request returns 400 error!
2020-03-02 21:31:24,082 - INFO - Instagram's error message: challenge_required
2020-03-02 21:31:24,082 - INFO - Error type: checkpoint_challenge_required
2020-03-02 21:31:24,082 - INFO - Going to comment medias by ceramah hashtag
Traceback (most recent call last):
  File "comment_hashtags.py", line 32, in <module>
    bot.comment_hashtag(hashtag)
  File "C:\Users\nizar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot\bot\bot.py", line 920, in comment_hashtag
    return comment_hashtag(self, hashtag, amount)
  File "C:\Users\nizar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot\bot\bot_comment.py", line 110, in comment_hashtag
    medias = self.get_total_hashtag_medias(hashtag, amount)
  File "C:\Users\nizar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot\bot\bot.py", line 582, in get_total_hashtag_medias
    return get_total_hashtag_medias(self, hashtag, amount, filtration)
  File "C:\Users\nizar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot\bot\bot_get.py", line 139, in get_total_hashtag_medias
    medias = self.api.get_total_hashtag_feed(hashtag, amount)
  File "C:\Users\nizar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot\api\api.py", line 1493, in get_total_hashtag_feed
    self.get_hashtag_feed(hashtag_str, next_max_id)
  File "C:\Users\nizar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot\api\api.py", line 1170, in get_hashtag_feed
    ).format(hashtag=hashtag, max_id=max_id, rank_token=self.rank_token)
  File "C:\Users\nizar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot\api\api.py", line 634, in rank_token
    return "{}_{}".format(self.user_id, self.uuid)
  File "C:\Users\nizar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instabot\api\api.py", line 630, in user_id
    return self.cookie_dict["ds_user_id"]
KeyError: 'ds_user_id'
```

**To Reproduce**

(EXAMPLE:) Steps to reproduce the behavior:
cd examples\comment
python comment_hashtags.py comments.txt ceramah videoislam fotoislam

**Expected behavior**

**Additional context**

**Version**

Python version (Python 3.8.1)
OS: Win 10

**Comment by nizarganteng** [comment]
how to fix this problem?
