### ISSUE TITLE
like_and_follow_your_last_media_likers.py TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by Plushkin** [ohld/igbot#145]
RESTART: /Users/Plushkin/Downloads/instabot-master/examples/like_and_follow_your_last_media_likers.py 
2017-03-26 20:44:21,856 - INFO - Instabot Started
Which account do you want to use? (Type number)
1: yvemtwins
0: add another account.
-1: delete all accounts.
1
2017-03-26 20:44:25,853 - INFO - Login success as yvemtwins!
Traceback (most recent call last):
  File "/Users/Plushkin/Downloads/instabot-master/examples/like_and_follow_your_last_media_likers.py", line 47, in <module>
    like_and_follow_your_feed_likers(bot)
  File "/Users/Plushkin/Downloads/instabot-master/examples/like_and_follow_your_last_media_likers.py", line 34, in like_and_follow_your_feed_likers
    return like_and_follow_media_likers(bot, last_media, nlikes=3)
  File "/Users/Plushkin/Downloads/instabot-master/examples/like_and_follow_your_last_media_likers.py", line 26, in like_and_follow_media_likers
    for user in tqdm(bot.get_media_likers(media), desc="Media likers"):
  File "/Users/Plushkin/Downloads/instabot-master/examples/../instabot/bot/bot.py", line 214, in get_media_likers
    return get_media_likers(self, media_id)
  File "/Users/Plushkin/Downloads/instabot-master/examples/../instabot/bot/bot_get.py", line 117, in get_media_likers
    return self.filter_users(self.LastJson["users"])
TypeError: 'bool' object is not callable

**Comment by rasperepodvipodvert** [comment]
У меня такое случается, когда я много запросов фигачу...

**Comment by ohld** [comment]
@rasperepodvipodvert Нужно подумать, где лучше всего расставить малые задержки, чтобы не банили.

**Comment by rasperepodvipodvert** [comment]
уже не банит!

**Comment by ohld** [comment]
Сделай тогда, пожалуйста, Pull request с этим дилеем. Обновим версию.
