### ISSUE TITLE
Problem with ultimate_schedule

### ISSUE THREAD

**Issue by chamo1116** [ohld/igbot#153]
When i run with docker, print "ImportError: No module named schedule" help pls.

**Comment by chamo1116** [comment]
i´ve installed schedule "pip install schedule" is already

**Comment by ohld** [comment]
Did you install schedule inside docker? 
Does pip and python commands have the save python version?

**Comment by chamo1116** [comment]
Thank you so much!!!!!!!

**Comment by chamo1116** [comment]
When i run the script, do i have to copy the txt files?

2017-03-29 20:22:00,836 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/si/fetch_headers/?challenge_type=signup&guid=4c78be5a51f04ccd9d4556b07c72737f (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4c5feb4d30>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2017-03-29 20:22:00,836 - INFO - ULTIMATE script. 24hours save
Can't find 'username_database.txt' file.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/random.py", line 253, in choice
    i = self._randbelow(len(seq))
  File "/usr/local/lib/python3.4/random.py", line 230, in _randbelow
    r = getrandbits(k)          # 0 <= r < 2**k
ValueError: number of bits must be greater than zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/kmkmx/ultimate.py", line 18, in <module>
    random_user=random.choice(random_user_file)
  File "/usr/local/lib/python3.4/random.py", line 255, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence
2017-03-29 20:22:00,837 - INFO - Bot stopped. Worked: 0:00:45.778624

**Comment by chamo1116** [comment]
This is my dockerfile
FROM python:3.4
WORKDIR /opt/app
COPY . /opt/app
COPY requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt
RUN pip install schedule

**Comment by chamo1116** [comment]
when i run print this one
 WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/si/fetch_headers/?challenge_type=signup&guid=9f7a0f76890d41578cc3185f3a678267 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f114b3cc0>: Failed to establish a new connection: [Errno 111] Connection refused',)))

**Comment by alblz** [comment]
I have the same problem
How did you fix it?

**Comment by chamo1116** [comment]
In the dockerfile you have to install the schedule 
"RUN pip install schedule"
