### ISSUE TITLE
Help me with this error

### ISSUE THREAD

**Issue by stanley747** [ohld/igbot#257]
root@kali:~/Desktop/instabot/examples# python unfollow_non_followers.py 
Traceback (most recent call last):
  File "unfollow_non_followers.py", line 14, in <module>
    from instabot import Bot
  File "/root/Desktop/instabot/examples/../instabot/__init__.py", line 1, in <module>
    from .api import API
  File "/root/Desktop/instabot/examples/../instabot/api/__init__.py", line 1, in <module>
    from .api import API
  File "/root/Desktop/instabot/examples/../instabot/api/api.py", line 11, in <module>
    from tqdm import tqdm
ImportError: No module named tqdm

**Comment by simongomez95** [comment]
Did you install dependencies before trying to run the example?

**Comment by thestation** [comment]
Just run the commands in the readme section. Open terminal and type "pip -U install instabot" -no quotations.
