### ISSUE TITLE
multi_script_CLI.py is not following anyone

### ISSUE THREAD

**Issue by gorillabu** [ohld/igbot#261]
2017-07-07 02:42:22,308 Follow followers of: 
2017-07-07 02:42:24,432 Going to follow 64 users.
2017-07-07 02:46:06,990 DONE: Total followed 0 users.

also I can't run most of the .py file but a few...

some of the error encounted as below:

w_user_followers.py 
usage: follow_user_followers.py [-h] [-u U] [-p P] [-proxy PROXY]
                                users [users ...]
follow_user_followers.py: error: the following arguments are required: users

**Comment by ofou** [comment]
same problem here when using any *follow* example :cry: 

```
Traceback (most recent call last):
  File "infinity_hashtags_follower.py", line 25, in <module>
    proxy=args.proxy)
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot.py", line 148, in login
    self.prepare()
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot.py", line 159, in prepare
    filter(None, map(self.convert_to_user_id, self.whitelist)))
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot.py", line 243, in convert_to_user_id
    return convert_to_user_id(self, usernames)
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot_get.py", line 158, in convert_to_user_id
    if smth[0] == "@":  # cut first @
IndexError: string index out of range

```

**Comment by 1mahdimf** [comment]
same problem in follow,like,...

**Comment by kushpvo** [comment]
I'm also getting the same. 

 DONE: Total followed 0 users.

**Comment by sudoguy** [comment]
The latest update solves this problems

**Comment by kushpvo** [comment]
I pulled the latest update, i deleted the setup and started from scratch
But still the same problem.

**Comment by sudoguy** [comment]
@kushpvo did you remove instabot from pip?

**Comment by ohld** [comment]
Should be fixed in current version.
