### ISSUE TITLE
repost not working

### ISSUE THREAD

**Issue by morier** [ohld/igbot#315]
i see this error every time i run it

Traceback (most recent call last):
  File "C:\Users\user\Desktop\instabot-master\examples\repost_best_photos_from_users.py", line 93, in <module>
    repost_best_photos(bot, users, args.amount)
  File "C:\Users\user\Desktop\instabot-master\examples\repost_best_photos_from_users.py", line 27, in repost_best_photos
    repost_photo(my_bot, media)
  File "C:\Users\user\Desktop\instabot-master\examples\repost_best_photos_from_users.py", line 65, in repost_photo
    photo_path = my_bot.download_photo(new_media_id, description=True)
  File "E:\program file\lib\site-packages\instabot\bot\bot.py", line 335, in download_photo
    return download_photo(self, media_id, path, filename, description)
  File "E:\program file\lib\site-packages\instabot\bot\bot_photo.py", line 24, in download_photo
    f.write(caption)
  File "E:\program file\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>

**Comment by sudoguy** [comment]
Try to use Python3

**Comment by morier** [comment]
i use python3

**Comment by ohld** [comment]
Please use the Issue template if you want to receive help.
