### ISSUE TITLE
Unable to like - Request return 400 Error!

### ISSUE THREAD

**Issue by orcunbaslak** [ohld/igbot#328]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: Python 2.7.9

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

It's the ultimate_schedule script with minimal changes. No python error, script runs fine.

Error/Debug Log:

2017-09-09 16:22:25,288 - INFO - Instabot Started
2017-09-09 16:22:26,469 - INFO - Login success as xxxxxx!
2017-09-09 16:22:26,469 - INFO - ULTIMATE script. 24hours save
2017-09-09 17:22:27,054 - INFO - Stats saved at 2017-09-09 17:22:27.
2017-09-09 18:22:26,802 - INFO - Liking timeline feed:
2017-09-09 18:22:27,236 - INFO - Stats saved at 2017-09-09 18:22:27.
2017-09-09 18:22:27,532 - INFO - Received 10 medias.
2017-09-09 18:22:27,533 - INFO - After filtration 1 medias left.
2017-09-09 18:22:27,533 - INFO - Going to like 1 medias.
  0%|          | 0/1 [00:00<?, ?it/s]2017-09-09 18:22:27,848 - WARNING - Request return 400 error!
2017-09-09 18:22:37,857 - INFO - DONE: Total liked 0 medias.
2017-09-09 19:22:27,015 - INFO - Going to like media with hashtag #gunesenerjisi.
2017-09-09 19:22:27,444 - INFO - Stats saved at 2017-09-09 19:22:27.
2017-09-09 19:22:28,916 - INFO - Received 62 medias.
2017-09-09 19:22:28,917 - INFO - After filtration 7 medias left.
2017-09-09 19:22:28,917 - INFO - Going to like 7 medias.
                                     2017-09-09 19:22:29,264 - WARNING - Request return 400 error!
  0%|          | 0/7 [00:00<?, ?it/s]
2017-09-09 19:22:39,276 - INFO - DONE: Total liked 0 medias.
---
```
### Describe your issue

Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.

I have tried the same script on my own computer, on a VPS and on an other computer. I'm getting the 400 error for likes. Even if the IP changes; the like ban continues. 

I also tested a chrome addon called Everliker which works fine (It's a barebone addon that just does web based liking. No follow/unfollow/comment etc).

Whe I worked my way thru the files I saw the config.py where you stored the user-agent and other signature related stuff. I believe since everyone using the same signature for Android  9.2 with IG_SIG_KEY = '012a54f51c49aa8c5c322416ab1410909add32c966bbaa0fe3dc58ac43fd7ede'; It's dead easy for Instagram to tag people who use the python script and avoid liking using instabot while allowing their app on iphone and web to work. 

Is there a way to update this value to a much more current one and try again? I don't believe VPNs, proxies, different IPs will work since we are the only ones with the red riding hood.

Br,

**Comment by popadiys** [comment]
this IG_SIG_KEY key comes from reverse engineering their native app. So it is not really dead easy to tag people and ban them. Not sure what is happening, since other bots have similar issues now.

**Comment by orcunbaslak** [comment]
IG_SIG_KEY is tied to a user-agent. Even if you change one letter in the user-agent; It does not work. So people with the combination of user-agent and IG_SIG_KEY in the config.py can be easily throttled. 

Do you have an other user-agent that works with the IG_SIG_KEY?

Br,

**Comment by popadiys** [comment]
IG_SIG_KEY is tied to the version of the IG app. I personally updated the IG_SIG_KEY and the user agent according to the latest in https://github.com/mgp25/Instagram-API and https://github.com/LevPasha/Instagram-API-python (from the later is taken this bot api code.)

**Comment by furnacemfg** [comment]
@popadiys Did updating the IG_SIG_KEY resolve this issue for you?

**Comment by popadiys** [comment]
@furnacemfg I've never faced the issue myself. But I prefer to have the later IG_SIG_KEY settings than an 3 years old one.

**Comment by furnacemfg** [comment]
@popadiys Makes sense. IG_SIG_KEY was simple enough to hunt down. Is it possible to update IG_SIG_KEY without updating the USER_AGENT or are the two tied together? 

The string replacement for User Agent in https://github.com/mgp25/Instagram-API is fairly involved: 

`const USER_AGENT_FORMAT = 'Instagram %s Android (%s/%s; %s; %s; %s; %s; %s; %s; %s)';`

**Comment by Kjartansson** [comment]
Is there  a guide to get a new IG_SIG_KEY i also get the 400 error

**Comment by Nader-abdi** [comment]
I have this problem, please provide a review and possible solution

**Comment by bardascat** [comment]
same problem , 400 error !

**Comment by ugurozturk** [comment]
same problem 400 error

**Comment by pxtyr** [comment]
400 error means you are showing spam activity and Instagram blocks this. 
There is no way around this as it is (probably) tracked by username not nescesarilyl the IG_SIG or other session identifiers.

If you stop spamming Instagram you won't get a 400 thrown at you

**Comment by ugurozturk** [comment]
2017-11-12 01:26:58,533 - INFO - Going to like media with hashtag #bilgisayar.
2017-11-12 01:27:00,556 - INFO - Received 85 medias.
2017-11-12 01:27:00,557 - INFO - After filtration 66 medias left.
2017-11-12 01:27:00,557 - INFO - Going to like 66 medias.
  0%|                                                    | 0/66 [00:00<?, ?it/s]2017-11-12 01:27:01,226 - ERROR - Request return 400 error!
2017-11-12 01:27:01,227 - INFO - Instagram error message: feedback_required
2017-11-12 01:27:11,240 - INFO - DONE: Total liked 0 medias.
2017-11-12 01:27:11,241 - INFO - Going to follow 71 users.

 Going to follow 71 user_ids ...

 After filtering followedlist.txt and skippedlist.txt, [ 6 ] user_ids left to follow.

 ===> Going to Follow user_id: 1077368974                 | 0/6 [00:00<?, ?it/s]

 Own following list is empty , downloading ...

 Already following , Skipping

 ===> Going to Follow user_id: 4349421672         | 1/6 [00:04<00:22,  4.55s/it]

 Already following , Skipping

 ===> Going to Follow user_id: 6040552570         | 2/6 [00:06<00:13,  3.44s/it]

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 144, in run
    for instance in self.tqdm_cls._instances:
  File "/usr/lib/python3.6/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration

**Comment by njhughes-01** [comment]
Anybody care to share thier new config with new ig sig I have one account that's working one that's 400 same computer different i.p. addresses

**Comment by AKwoKWH** [comment]
I have same issue, 
but after turning of using cookie, then it works fine.
