### ISSUE TITLE
No module named instabot.api

### ISSUE THREAD

**Issue by ugurozturk** [ohld/igbot#391]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:
Python 3.6.3

Code:

```python
Fresh start from examples/ultimate/ultimate.py
```

Error/Debug Log:

```python
> python ultimate.py
Traceback (most recent call last):
  File "ultimate.py", line 18, in <module>
    from instabot import Bot
  File "C:\Users\taran\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instabot-0.3.3.20-py3.6.egg\instabot\__init__.py", line 1, in <module>
ModuleNotFoundError: No module named 'instabot.api'
```

---

### Describe your issue

Did clone repo and made "python setup.py install" that is all. After that tried the bot but it failed

**Comment by ugurozturk** [comment]
After doing python3 setup.py install

```
root@ss:~/instabot/examples/ultimate# python3 ultimate.py
Traceback (most recent call last):
  File "ultimate.py", line 7, in <module>
    from instabot import Bot
  File "/usr/local/lib/python3.5/dist-packages/instabot-0.3.3.20-py3.5.egg/instabot/__init__.py", line 1, in <module>
ImportError: No module named 'instabot.api'

```

**Comment by ugurozturk** [comment]
Fixed again by doing "sudo pip install -U instabot" in examples/ultimate
