### ISSUE TITLE
Like Media by Location giving error

### ISSUE THREAD

**Issue by miranthajayatilake** [ohld/igbot#420]
```
Traceback (most recent call last):
  File "like_medias_by_location.py", line 89, in <module>
    print(u'{0}. {1}'.format(n, location['title']))
  File "C:\Users\miranthaj\AppData\Roaming\Python\Python35\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Users\miranthaj\AppData\Roaming\Python\Python35\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Users\miranthaj\AppData\Roaming\Python\Python35\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\miranthaj\AppData\Roaming\Python\Python35\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Users\miranthaj\AppData\Local\Programs\Python\Python35\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 4-12: character maps to <undefined>
```

### Describeing issue

When I run like like_medias_by_location.py the above error pops up. Seems like something to do with encoding as I understand. Would appreciate help to clarify this. 
Thank you.

**Comment by miranthajayatilake** [comment]
Ok I figured out the problem. Apparently this has something to do with windows. 
execute this before running the script
`chcp 65001`

It worked! Thank you for this great project! Keep up the good work!

**Comment by luke-edward** [comment]
how to run that script
chcp 65001
