### ISSUE TITLE
Proxy issue in instabot version 0.3.5.3

### ISSUE THREAD

**Issue by negswell** [ohld/igbot#475]
### Purpose of your issue?
- [X ] Bug report (encountered problems/errors)
- [X ] Other

Code:
---
From instabot import Bot 
instagrambot=Bot()
instagrambot.login(username='solomolo5689', password=igpassword,proxy='username:password@host:port')
#username/password/host/port have been hidden due to privacy 
#proxy used is ipv4 and ipv6 compatible ,protocol HTTP 
Traceback (most recent call last):
---
```
2018-03-24 20:02:23,296 - INFO - Instabot Started
2018-03-24 20:02:23,301 - WARNING - Not supported proxy scheme login
Traceback (most recent call last):
  File "C:\Users\negia\Desktop\host\my_env\elusive\leechgroupfunctions.py", line 18, in <module>
    instagrambot.login(username='solomolo5689', password=igpassword,proxy='login:password@host:port')
  File "C:\Users\negia\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instabot\bot\bot.py", line 183, in login
    self.prepare()
  File "C:\Users\negia\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instabot\bot\bot.py", line 193, in prepare
    self.whitelist = check_whitelists(self)
  File "C:\Users\negia\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instabot\bot\bot_support.py", line 46, in check_whitelists
    'friends_{0}.txt'.format(self.user_id),
AttributeError: 'Bot' object has no attribute 'user_id'
```

---

### Describe your issue
Hello ,
I recently bought 5 dedicated proxies and none of them are working with instabot .Not able to login using any of my proxies , can i know what does not supported proxy scheme mean and how i can fix this issue .
Also i can't understand why **AttributeError: 'Bot' object has no attribute 'user_id'** is being raised ?

**Comment by negswell** [comment]
the issue has been fixed .

**Comment by heyton** [comment]
I have same problem. How do you fixed it?

**Comment by negswell** [comment]
use http proxies ,using this format ,proxy='http://username:password@ip_address:port'
