### ISSUE TITLE
Error on Ultimate.py

### ISSUE THREAD

**Issue by zeroyjk** [ohld/igbot#526]
```
Traceback (most recent call last):
  File "ultimate.py", line 15, in <module>
    bot = Bot(comments_file=config.COMMENTS_FILE, blacklist=config.BLACKLIST_FILE, whitelist=config.WHITELIST_FILE)
TypeError: __init__() got an unexpected keyword argument 'blacklist'
```
When i run.. i getting this error.. How to fix it?

**Comment by zeroyjk** [comment]
Also when i run follow_user_followers.py (USER NAME) i getting this error.

```
2018-05-04 12:14:34,378 - INFO - Follow followers of: abc123
Consider temporarily saving the result of this big operation. This will take a while.

Traceback (most recent call last):                                              
  File "follow_user_followers.py", line 27, in <module>
    bot.follow_followers(username)
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot.py", line 433, in follow_followers
    return follow_followers(self, user_id, nfollows)
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot_follow.py", line 75, in follow_followers
    followers = self.get_user_followers(user_id, nfollows)
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot.py", line 333, in get_user_followers
    return get_user_followers(self, user_id, nfollows)
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot_get.py", line 166, in get_user_followers
    followers = self.api.get_total_followers(user_id, nfollows)
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api.py", line 596, in get_total_followers
    user_id, amount, 'followers')
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api.py", line 571, in get_total_followers_or_followings
    get(user_id, next_max_id)
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api.py", line 423, in get_user_followers
    return self.send_request(url)
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api.py", line 171, in send_request
    self.last_json = json.loads(response.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 50306 (char 50305)
2018-05-04 12:14:40,681 - INFO - Bot stopped. Worked: 2:11:53.277635
2018-05-04 12:14:40,682 - INFO - Total requests: 4294
```

**Comment by basnijholt** [comment]
You are using the new version of instabot, but an old version of the
script. Please update the script, find it in examples.
