### ISSUE TITLE
Error on follow_user_followers.py

### ISSUE THREAD

**Issue by zeroyjk** [ohld/igbot#569]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
```

Traceback (most recent call last):                                            
  File "follow_user_followers.py", line 27, in <module>
    bot.follow_followers(username)
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot.py", line 433, in follow_followers
    return follow_followers(self, user_id, nfollows)
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot_follow.py", line 75, in follow_followers
    followers = self.get_user_followers(user_id, nfollows)
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot.py", line 333, in get_user_followers
    return get_user_followers(self, user_id, nfollows)
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot_get.py", line 166, in get_user_followers
    followers = self.api.get_total_followers(user_id, nfollows)
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api.py", line 596, in get_total_followers
    user_id, amount, 'followers')
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api.py", line 571, in get_total_followers_or_followings
    get(user_id, next_max_id)
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api.py", line 423, in get_user_followers
    return self.send_request(url)
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api.py", line 171, in send_request
    self.last_json = json.loads(response.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 52913 (char 52912)
2018-06-11 08:37:35,724 - INFO - Bot stopped. Worked: 0:16:58.747704
2018-06-11 08:37:35,725 - INFO - Total requests: 8349
```

**Comment by basnijholt** [comment]
Thanks for reporting, this is fixed by https://github.com/instagrambot/instabot/commit/b529a8ee9b10b88aad021a18e2d39dd586866815.
