### ISSUE TITLE
error 400 on like

### ISSUE THREAD

**Issue by RobertoBrandini** [ohld/igbot#629]
all my acounts return error 400 

2018-08-30 10:43:30,364 - INFO - Instabot Started
2018-08-30 10:43:30,364 - INFO - Logged-in successfully as 'robertobrandini' using the cookie!
2018-08-30 10:43:30,364 - INFO - Going to like media with hashtag #nerd.
Getting hashtag media.: 0it [00:00, ?it/s]
2018-08-30 10:43:30,797 - ERROR - Request returns 400 error!
2018-08-30 10:43:30,803 - INFO - Instagram's error message: login_required
Traceback (most recent call last):
  File "..\infinity_hashtags_liker.py", line 31, in <module>
    bot.like_hashtag(hashtag)
  File "D:\Fabrica_Python\instagrambot\examples\instabot\bot\bot.py", line 383, in like_hashtag
    return like_hashtag(self, hashtag, amount)
  File "D:\Fabrica_Python\instagrambot\examples\instabot\bot\bot_like.py", line 62, in like_hashtag
    medias = self.get_total_hashtag_medias(hashtag, amount)
  File "D:\Fabrica_Python\instagrambot\examples\instabot\bot\bot.py", line 303, in get_total_hashtag_medias
    return get_total_hashtag_medias(self, hashtag, amount, filtration)
  File "D:\Fabrica_Python\instagrambot\examples\instabot\bot\bot_get.py", line 83, in get_total_hashtag_medias
    medias = self.api.get_total_hashtag_feed(hashtag, amount)
  File "D:\Fabrica_Python\instagrambot\examples\instabot\api\api.py", line 624, in get_total_hashtag_feed
    items = last_json['items']
KeyError: 'items'
2018-08-30 10:43:31,537 - ERROR - Request returns 400 error!
2018-08-30 10:43:31,537 - INFO - Instagram's error message: login_required
2018-08-30 10:43:31,537 - INFO - Bot stopped. Worked: 1 day, 1:14:26.487057
2018-08-30 10:43:31,537 - INFO - Total likes: 4
2018-08-30 10:43:31,537 - INFO - Total requests: 14263

**Comment by basnijholt** [comment]
Update to master with 
```
pip uninstall -y instabot
pip install https://github.com/instagrambot/instabot/archive/master.zip
```

**Comment by basnijholt** [comment]
Update to master with 
```
pip uninstall -y instabot
pip install https://github.com/instagrambot/instabot/archive/master.zip
```
and try again.

@sudoguy should we release a new version to pip where this fix is included?

**Comment by RobertoBrandini** [comment]
same problem

**Comment by RobertoBrandini** [comment]
solved the problem deleting cookie.txt
