### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by dogukanaras** [ohld/igbot#682]
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: python 3.7.0 already installed

Code:

```python
import os
import sys
import time
import random
from instabot import Bot
sys.setdefaultencoding('utf-8')
from instapy import InstaPy


def job():
	username='*****'
	password='******'
	hashtags = ['izmir']
	bot = Bot(like_delay=random.randint(50,100),follow_delay=random.randint(50,100),unfollow_delay=random.randint(30,70),stop_words=stop_words)
	bot.login(username=username, password=password)
	bot.unfollow_non_followers()
	bot.save_user_stats(username, os.path.abspath('logs'))
	bot.logout()
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from instabot import Bot
  File "/Users/username/Library/Mobile Documents/com~apple~CloudDocs/instabot/*****/instabot/__init__.py", line 1, in <module>
    from .api import API
  File "/Users/username/Library/Mobile Documents/com~apple~CloudDocs/instabot/*****/instabot/api/__init__.py", line 1, in <module>
    from .api import API
  File "/Users/username/Library/Mobile Documents/com~apple~CloudDocs/instabot/*****/instabot/api/api.py", line 10, in <module>
    import requests
ImportError: No module named requests
```

---

### Describe your issue
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (2.11.1)
"requests" package, even though it says to install

**Comment by mstikharev** [comment]
May be you are execute script not from virtual environment or you local env doesn't have `requests`? Check it first :)

**Comment by dogukanaras** [comment]
I tried it in the local directory, but nothing changed.
I was working both ways before. But it doesn't work anymore

```python
Traceback (most recent call last):
  File "unfollow_non_followers.py", line 13, in <module>
    from instabot import Bot
  File "/Users/dogukanaras/Desktop/instabot/examples/../instabot/__init__.py", line 1, in <module>
    from .api import API
  File "/Users/dogukanaras/Desktop/instabot/examples/../instabot/api/__init__.py", line 1, in <module>
    from .api import API
  File "/Users/dogukanaras/Desktop/instabot/examples/../instabot/api/api.py", line 15, in <module>
    import requests
ImportError: No module named requests

```
