### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by smolyakov26** [ohld/igbot#771]
any fix for error 403?

**Comment by TiasTias** [comment]
My bot has stopped working and I just get 404s and 403s. It had been working for weeks and then just a day ago it stopped working properly. 

2019-01-20 18:14:54,793 - INFO - ULTIMATE script. Safe to run 24/7!
2019-01-20 19:00:00,725 - INFO - Going to like and follow recent post likers of borkeberlin.
2019-01-20 19:00:02,903 - ERROR - Request returns 403 error!
2019-01-20 19:00:03,769 - ERROR - Request returns 404 error!
2019-01-20 19:00:03,769 - WARNING - This is a closed account.
2019-01-20 19:14:55,270 - ERROR - Request returns 403 error!
2019-01-20 20:00:00,830 - INFO - Going to like and follow recent post likers of lenasberlin.
2019-01-20 20:00:01,312 - ERROR - Request returns 403 error!
2019-01-20 20:00:02,289 - ERROR - Request returns 404 error!
2019-01-20 20:00:02,289 - WARNING - This is a closed account.
2019-01-20 20:14:56,155 - ERROR - Request returns 403 error!
2019-01-20 21:00:00,311 - INFO - Going to like media with hashtag #igersberlin.
Getting hashtag media.:   0%|                                            | 0/50 [00:00<?, ?it/s]2019-01-20 21:00:01,116 - ERROR - Request returns 403 error!
2019-01-20 21:00:01,128 - INFO - Nothing to like.                                               
2019-01-20 21:14:57,041 - ERROR - Request returns 403 error!
2019-01-20 22:00:00,911 - ERROR - Request returns 403 error!
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "ultimate.py", line 62, in like_location_feed
    finded_location = bot.api.last_json['items'][0]
KeyError: 'items'

2019-01-20 22:15:36,579 - ERROR - Request returns 403 error!
2019-01-20 23:00:00,226 - INFO - Going to like media with hashtag #photography.
Getting hashtag media.:   0%|                                            | 0/22 [00:00<?, ?it/s]2019-01-20 23:00:00,766 - ERROR - Request returns 403 error!
2019-01-20 23:00:00,779 - INFO - Nothing to like.                                               
2019-01-20 23:14:57,660 - ERROR - Request returns 403 error!
2019-01-21 00:14:59,366 - ERROR - Request returns 403 error!
2019-01-21 01:00:00,162 - INFO - Creating non-followers list

`bot.following` is empty, will download.
2019-01-21 01:00:01,673 - ERROR - Request returns 403 error!

`bot.followers` is empty, will download.
2019-01-21 01:00:01,831 - ERROR - Request returns 403 error!
2019-01-21 01:00:01,831 - INFO - Done.
2019-01-21 01:14:58,418 - ERROR - Request returns 403 error!
2019-01-21 02:14:58,779 - ERROR - Request returns 403 error!
2019-01-21 03:00:00,044 - INFO - Unfollowing non-followers.

 ===> Start unfollowing non-followers <===
0it [00:00, ?it/s]

 ===> Unfollow non-followers done! <===
2019-01-21 03:14:59,648 - ERROR - Request returns 403 error!
2019-01-21 04:14:59,980 - ERROR - Request returns 403 error!
2019-01-21 05:15:00,251 - ERROR - Request returns 403 error!
2019-01-21 06:15:01,260 - ERROR - Request returns 403 error!
2019-01-21 07:15:04,411 - ERROR - Request returns 403 error!
2019-01-21 08:15:02,988 - ERROR - Request returns 403 error!
2019-01-21 09:00:00,078 - INFO - Going to like media with hashtag #kreuzberg.
Getting hashtag media.:   0%|                                            | 0/64 [00:00<?, ?it/s]2019-01-21 09:00:00,444 - ERROR - Request returns 403 error!
2019-01-21 09:00:00,492 - INFO - Nothing to like.                                               
2019-01-21 09:15:03,758 - ERROR - Request returns 403 error!
2019-01-21 10:00:00,731 - ERROR - Request returns 403 error!
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "ultimate.py", line 62, in like_location_feed
    finded_location = bot.api.last_json['items'][0]
KeyError: 'items'

2019-01-21 10:15:04,003 - ERROR - Request returns 403 error!

**Comment by Ritchie001** [comment]
hello Alex i'm experiencing the same thing after the fix (405) account worked fine today i got 403 and 404 like you

**Comment by smolyakov26** [comment]
SOLVED 403 error 
delete cookies.txt in examples every time you use bot , or set bot not to use cookies

**Comment by TiasTias** [comment]
I deleted the cookies.txt but now when I run I get this:

2019-01-22 21:56:33,157 - INFO - Logged-in successfully as 'thisistias'!
2019-01-22 21:56:33,158 - INFO - Saved cookie!
2019-01-22 21:56:33,158 - INFO - ULTIMATE script. Safe to run 24/7!
  0%|                                                                               | 0/35 [00:00<?, ?it/s]2019-01-22 22:00:04,283 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:00:15,644 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:00:26,769 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:00:31,263 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:00:34,964 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:00:44,452 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:00:54,493 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:01:03,028 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:01:15,444 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:01:19,044 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:01:26,193 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:01:29,564 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:01:38,204 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:01:45,448 - ERROR - Request returns 405 error!

Media ID error!

**Comment by maxdevblock** [comment]
405
Uninstall `pip` installed version and `git clone` latest update

**Comment by ohld** [comment]
we have been uploaded a new version to pip: run to update
``` bash 
pip install -U instabot
```

**Comment by stanus74** [comment]
it only works for me with delete the cookie file

**Comment by ohld** [comment]
@maxdevblock looks like Instagram really changed the cookies algorithm. I'll set `use_cookie=False` by default.

**Comment by stanus74** [comment]
i which file? api/api.py  or bot/bot.py? 

thank you

**Comment by stanus74** [comment]
the cookie file generated again and don't work

**Comment by ohld** [comment]
Have you update the Instsbot? 
pip install -U instsbot

**Comment by ofou** [comment]
> it only works for me with delete the cookie file

Deleting the cookie worked for me too :robot:

**Comment by stanus74** [comment]
did update - only delete cookie works

**Comment by ohld** [comment]
So after an update everything works? You just had to delete old cookie file and everything worked? Please describe your situation with more words. @stanus74

**Comment by tillkemper** [comment]
Got the same error, i am also forcing the bot not to use the cookie.

**Comment by Areahints** [comment]
if you're using both pip and git version, uninstall the pip version using `pip uninstall instabot`.

then cd into the instabot folder, `git pull` to get the latest version, `pip install requirements.txt` or you can open the .txt file and install the modules directly. the 403 and 404 error should be resolved then
