### ISSUE TITLE
Fix packedge requirements

### ISSUE THREAD

**Issue by voron434** [ohld/igbot#794]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [ x Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
[GCC 4.8.2] on linux
Collecting instabot
  Downloading https://files.pythonhosted.org/packages/bd/7a/5e37bd6e68d9c464415d55e46a351319136d58839a5e9fb2e8e799890507/instabot-0.8.0.tar.gz (49kB)
Building wheels for collected packages: instabot
  Running setup.py bdist_wheel for instabot: started
  Running setup.py bdist_wheel for instabot: finished with status 'done'
  Stored in directory: /home/runner/.cache/pip/wheels/51/88/b7/1f2e94145b6bc4695e64e705cb1bcb1da08f6be70582a7e650
Successfully built instabot
Installing collected packages: instabot
Successfully installed instabot-0.8.0
You are using pip version 9.0.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Repl.it: package installation success

 Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from instabot import Bot
  File "/home/runner/.site-packages/instabot/__init__.py", line 1, in <module>
    from .api import API
  File "/home/runner/.site-packages/instabot/api/__init__.py", line 1, in <module>
    from .api import API
  File "/home/runner/.site-packages/instabot/api/api.py", line 19, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

---

### Describe your issue

In last commits you broke package requirements. Sometimes it`s `tqdm` ( used for progress-bars), my collegue  got another traceback willing to install `instabot`:

```
>>> from instabot import Bot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/evgeny/code/PyCourses/smm-test-5/env/lib/python3.6/site-packages/instabot/__init__.py", line 1, in <module>
    from .api import API
  File "/home/evgeny/code/PyCourses/smm-test-5/env/lib/python3.6/site-packages/instabot/api/__init__.py", line 1, in <module>
    from .api import API
  File "/home/evgeny/code/PyCourses/smm-test-5/env/lib/python3.6/site-packages/instabot/api/api.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/evgeny/code/PyCourses/smm-test-5/env/lib/python3.6/site-packages/instabot/__init__.py", line 1, in <module>
    from .api import API
  File "/home/evgeny/code/PyCourses/smm-test-5/env/lib/python3.6/site-packages/instabot/api/__init__.py", line 1, in <module>
    from .api import API
  File "/home/evgeny/code/PyCourses/smm-test-5/env/lib/python3.6/site-packages/instabot/api/api.py", line 18, in <module>
    import six.moves.urllib as urllib
ModuleNotFoundError: No module named 'six

>>> from instabot import Bot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/evgeny/code/PyCourses/smm-test-5/env/lib/python3.6/site-packages/instabot/__init__.py", line 1, in <module>
    from .api import API
  File "/home/evgeny/code/PyCourses/smm-test-5/env/lib/python3.6/site-packages/instabot/api/__init__.py", line 1, in <module>
    from .api import API
  File "/home/evgeny/code/PyCourses/smm-test-5/env/lib/python3.6/site-packages/instabot/api/api.py", line 19, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

**Comment by ohld** [comment]
```pip install tqdm```
