### ISSUE TITLE
Default log file location should be configurable

### ISSUE THREAD

**Issue by DhruvRaiPuri** [ohld/igbot#833]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: Python 3.7.1 (refer - https://cloud.google.com/functions/docs/concepts/python-runtime) 
Code: 

```python
# Example code that will produce the error reported
from instabot import Bot
bot = Bot()
```

Error/Debug Log:

```python
Traceback (most recent call last): File "/env/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 349, in run_background_function _function_handler.invoke_user_function(event_object) File "/env/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 215, in invoke_user_function return call_user_function(request_or_event) File "/env/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 212, in call_user_function event_context.Context(**request_or_event.context)) File "/user_code/main.py", line 27, in loadInstaFeedToBigQuery bot = Bot() File "/env/lib/python3.7/site-packages/instabot/bot/bot.py", line 97, in __init__ self.api = API(device=device) File "/env/lib/python3.7/site-packages/instabot/api/api.py", line 43, in __init__ fh = logging.FileHandler(filename='instabot.log') File "/opt/python3.7/lib/python3.7/logging/__init__.py", line 1092, in __init__ StreamHandler.__init__(self, self._open()) File "/opt/python3.7/lib/python3.7/logging/__init__.py", line 1121, in _open return open(self.baseFilename, self.mode, encoding=self.encoding) OSError: [Errno 30] Read-only file system: '/user_code/instabot.log'
```

---

### Describe your issue
I am running instabot in Python Google Cloud Function environment. The default folder in which the code runs (/user_code) is read-only. 

The code in api.py which instantiates FileHandler for logger is harcoded in the package to 'instabot.log' due to which a read-only error is thrown by Cloud Function runtime as it attempts to write to '/user_code/instabot.log' which it can't. 

There should be a way to override the log file location to a different folder (in this case '/user_code/tmp' where 'tmp' is the only folder with write permission in a Google Cloud Function).

**Comment by ohld** [comment]
Agreed. Can you please code this and make a pull request?

**Comment by DhruvRaiPuri** [comment]
Sure, will work on it and submit a pull request.
