### ISSUE TITLE
Request returns 400 error

### ISSUE THREAD

**Issue by MacSweazy** [ohld/igbot#860]
2019-04-04 08:29:35,523 - INFO - Instabot Started
2019-04-04 08:29:36,419 - ERROR - Request returns 400 error!
2019-04-04 08:29:36,420 - INFO - Instagram's error message: challenge_required
2019-04-04 08:29:36,420 - INFO - Error type: checkpoint_challenge_required
2019-04-04 08:29:36,420 - INFO - Username or password is incorrect.

`bot.following` is empty, will download.
Traceback (most recent call last):
  File "unfollow_everyone.py", line 25, in <module>
    bot.unfollow_everyone()
  File "/usr/local/lib/python3.6/dist-packages/instabot/bot/bot.py", line 522, in unfollow_everyone
    return unfollow_everyone(self)
  File "/usr/local/lib/python3.6/dist-packages/instabot/bot/bot_unfollow.py", line 59, in unfollow_everyone
    self.unfollow_users(self.following)
  File "/usr/local/lib/python3.6/dist-packages/instabot/bot/bot.py", line 225, in following
    self._following = self.get_user_following(self.user_id)
  File "/usr/local/lib/python3.6/dist-packages/instabot/bot/bot.py", line 190, in user_id
    return self.api.user_id
  File "/usr/local/lib/python3.6/dist-packages/instabot/api/api.py", line 258, in user_id
    return self.cookie_dict['ds_user_id']
KeyError: 'ds_user_id'

**Comment by renevt** [comment]
Same here  afther changing ig password.

**Comment by m0o0hammad** [comment]
i'm same here

**Comment by zeing** [comment]
same here but  like

![image](https://user-images.githubusercontent.com/20161393/57997815-d9703b80-7af8-11e9-97f9-d1bffc4cb027.png)

**Comment by glisilghiro** [comment]
samve

> 2019-04-04 08:29:35,523 - INFO - Instabot Started
> 2019-04-04 08:29:36,419 - ERROR - Request returns 400 error!
> 2019-04-04 08:29:36,420 - INFO - Instagram's error message: challenge_required
> 2019-04-04 08:29:36,420 - INFO - Error type: checkpoint_challenge_required
> 2019-04-04 08:29:36,420 - INFO - Username or password is incorrect.
> 
> `bot.following` is empty, will download.
> Traceback (most recent call last):
> File "unfollow_everyone.py", line 25, in 
> bot.unfollow_everyone()
> File "/usr/local/lib/python3.6/dist-packages/instabot/bot/bot.py", line 522, in unfollow_everyone
> return unfollow_everyone(self)
> File "/usr/local/lib/python3.6/dist-packages/instabot/bot/bot_unfollow.py", line 59, in unfollow_everyone
> self.unfollow_users(self.following)
> File "/usr/local/lib/python3.6/dist-packages/instabot/bot/bot.py", line 225, in following
> self._following = self.get_user_following(self.user_id)
> File "/usr/local/lib/python3.6/dist-packages/instabot/bot/bot.py", line 190, in user_id
> return self.api.user_id
> File "/usr/local/lib/python3.6/dist-packages/instabot/api/api.py", line 258, in user_id
> return self.cookie_dict['ds_user_id']
> KeyError: 'ds_user_id'

Same error? Any solution?

**Comment by SelfMadeDev** [comment]
Same here! Did anybody find a solution?

**Comment by Kobaltauge** [comment]
Still got the problem. Probably because of an underscore in the user name.

**Comment by canpoyrazoglu** [comment]
Nope, no underscore in my username (it's just letters) and I'm also getting the same error. This is my first time trying this bot and I've followed all the steps correctly, and I'm getting the same error.

**Comment by canpoyrazoglu** [comment]
I was just entering my password incorrectly. Check that you are entering your correct password, and try to put quotation marks around your username and password:

`python3 like_hashtags.py -u 'yourusername' -p 'yourpassword'`

**Comment by llapieta** [comment]
Same issue here!!

**Comment by leoccyao** [comment]
You received an instagram checkpoint challenge. Use 
```
bot.login(ask_for_code=True)
```

Also see #1140

**Comment by Spixmaster** [comment]
> You received an instagram checkpoint challenge. Use
> 
> ```
> bot.login(ask_for_code=True)
> ```
> 
> Also see #1140

That is it! You saved my life!

**Comment by ohld** [comment]
@leoccyao Maybe it is worth to add this parameter by default?

**Comment by viktorvexacious** [comment]
> You received an instagram checkpoint challenge. Use
> 
> ```
> bot.login(ask_for_code=True)
> ```
> 
> Also see #1140

Exactly where am I supposed to insert this code?

**Comment by viktorvexacious** [comment]
@ohld Where should I place the code?

**Comment by KadabrahG** [comment]
> You received an instagram checkpoint challenge. Use
> bot.login(ask_for_code=True)
> 
> Also see #1140

Hey guys, where should we insert this line of code ? 
Thanks <3

**Comment by bruvv** [comment]
Closing this since its a very old issue. If this is still an issue please open a new one.
