### ISSUE TITLE
Chellenge required

### ISSUE THREAD

**Issue by mirlife** [ohld/igbot#946]
1
2019-06-12 07:17:19,434 - ERROR - Request returns 400 error!
2019-06-12 07:17:19,434 - INFO - Instagram's error message: challenge_required
2019-06-12 07:17:19,435 - INFO - Error type: checkpoint_challenge_required
2019-06-12 07:17:19,435 - INFO - Username or password is incorrect.
2019-06-12 07:17:19,444 - INFO - Instabot Started
2019-06-12 07:17:19,951 - ERROR - Request returns 400 error!
2019-06-12 07:17:19,952 - INFO - Instagram's error message: challenge_required
2019-06-12 07:17:19,952 - INFO - Error type: checkpoint_challenge_required
2019-06-12 07:17:19,952 - INFO - Username or password is incorrect.
2019-06-12 07:17:19,952 - CRITICAL - Not logged in!
Traceback (most recent call last):
  File "save_media_likers_to_file.py", line 26, in <module>
    last_user_med=get_last_user_medias(usernames)
  File "/home/MrTakedOfficial/topygram/instabot/examples/get_last_user_medias.py", line 17, in get_last_user_medias
    user_id=bot.get_user_id_from_username(username)
  File "/home/MrTakedOfficial/topygram/instabot/examples/../instabot/bot/bot.py", line 402, in get_user_id_from_username
    return get_user_id_from_username(self, username)
  File "/home/MrTakedOfficial/topygram/instabot/examples/../instabot/bot/bot_get.py", line 197, in get_user_id_from_username
    self.api.search_username(username)
  File "/home/MrTakedOfficial/topygram/instabot/examples/../instabot/api/api.py", line 861, in search_username
    return self.send_request(url)
  File "/home/MrTakedOfficial/topygram/instabot/examples/../instabot/api/api.py", line 169, in send_request
    raise Exception(msg)
Exception: Not logged in!

**Comment by reidmeyer** [comment]
same

**Comment by eduardoegos** [comment]
same. solving the challenge on my phone or the website doesn't help it. i can never login

**Comment by alex-grover** [comment]
this is a duplicate of #630
